### PR TITLE
INTERLOK-3742

### PR DESCRIPTION
**Pull request by aaron-mcgrath-adp**
## Motivation

It looks as though there might be a memory leak somewhere in the profiler code.  From Matt's last heap dumps it suggests that the micrometer registries are growing in size over time.

## Modification

Just in case there is some magic somewhere caching registry meters we now call clear on the newly created registry after we're done with it.  Previously we would simply allow it to be garbage collected.

## Result

Hoping to see the registry no longer growing in size over time.

### CODE REVIEW

**Review by mcwarman — APPROVED** [review]

**Comment by mcwarman** [comment]
Can the `PrometheusMeterRegistry` be reused?

**Comment by quotidian-ennui** [comment]
naiively calling CLEAR isn't going to cut it. You need to re-use the registry, and then not bind things again, if they are already bound.

```
      MetricProviders.getProviders().forEach( provider -> {
        try {
          provider.bindTo(prometheusRegistry);
        } catch (Exception e) {
          log.warn("Metric gathering failed, will try again on next request.");
          exceptionLogging(ADDITIONAL_DEBUG, "Stack trace from metric gathering failure :", e);
        }
      });
```

If we "run the chain through our heads" eventually we end up in JvmMetricsGenerator.

Which essentially does
```
Class.newInstance().bindTo(registry)
```

Which means that *every time we call on-message* we register a new instance of 10 JVM Metrics against a new registry. which means we then have to figure out how things are bound against the new registry.

And then if we look at something like `ClassLoaderMetrics` we can see that we're building a Gauge with a Strong Reference which means you have a memory leak right away. 
- Line 49 of ClassLoaderMetrics ->  Gauge.builder().register() -> Line 189 Gauge -> Use of StrongReferenceGaugeFunction implies that the GAUGE never goes out of scope.


Which means that

- MetricProviders can't create new instances of things (i.e JvmMetricsGenerator can't do class.newInstance())
- don't create a new rgistry every time in OnMessage

**Comment by quotidian-ennui** [comment]
@aaron-mcgrath-adp @mcwarman I made some changes, but of course it broke the tests.

**Review by quotidian-ennui — APPROVED** [review]
This will have to be revisited for 4.1

**Pull request merged**
